ALTER TABLE users ADD COLUMN IF NOT EXISTS auth2 BOOLEAN DEFAULT false;
UPDATE users SET auth2 = false WHERE auth2 IS NULL;
ALTER TABLE users ALTER COLUMN auth2 SET DEFAULT false;
ALTER TABLE users ALTER COLUMN auth2 SET NOT NULL;
